<a href="https://colab.research.google.com/github/dejettss/data-science-toolkitW1/blob/main/T3DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

a = np.array([[1,2],
                     [3,4]])
print(a)

[[1 2]
 [3 4]]


In [7]:
ran = np.random.randint(1,10,(3,4))
print(ran)

[[9 9 1 9]
 [5 3 8 4]
 [1 2 8 3]]


In [20]:
uy = np.ones((3,3))

zero = np.zeros((3,3))
print(zero)
print(" ")
print(uy)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [34]:
print("original:\n")
tr = np.random.randint(1,100, (3,6))
print(tr)

print("\n Transposed version: \n")

tr1 = tr.T
print(tr1)

original:

[[62 85 67 22 50 51]
 [71 67 50 83 33 47]
 [21 37 45 31 77 47]]

 Transposed version: 

[[62 71 21]
 [85 67 37]
 [67 50 45]
 [22 83 31]
 [50 33 77]
 [51 47 47]]


In [46]:
n = 2
p = 3
m = 4

X = np.random.randint(1, 10, (n,p))
Y = np.random.randint(1, 10, (p,m))
print(X)
print(" ")
print(Y)
Z = np.dot(X,Y)
print("\nThis is the dot of those:\n")
print(Z)

[[9 1 8]
 [9 2 1]]
 
[[9 8 3 4]
 [1 7 6 8]
 [5 2 5 5]]

This is the dot of those:

[[122  95  73  84]
 [ 88  88  44  57]]
